### ISSUE TITLE
Modified extended hotkeys not working

### ISSUE THREAD

**Issue by rodcleveland** [tashcan/bob#12]
When changing some of the hotkeys in the config they are not assigned. 

ie: changing 

`# Zoom in/out
zoom_in = 'KEYMINUS'
zoom_out = 'KEYPLUS'`

is not working. others are the same issue.

**Comment by tashcan** [comment]
Customizable hotkeys are only in a beta/pre-release version of this, which still has a couple issues to smooth out. The release version has fixed hotkeys.
Hopefully it'll be ready for public full release soon.

**Comment by netniV** [comment]
Hotkeys work off the alpha/beta builds.  One of those is available  that should work with the latest version of the game.
https://github.com/tashcan/bob/actions/runs/7814064954

**Comment by rodcleveland** [comment]
Thanks that did it. Anyone know what that locate function was moved to? Or can it be assigned in the config?
