### ISSUE TITLE
Makes the new update to the geame as of 02/6/24 crash

### ISSUE THREAD

**Issue by michaelcrossland1979** [tashcan/bob#17]
Every time it gets to just past the downloading the game state and getting ready to start and then the game crashes out. However if you just add a ".old" to the dll the game runs fine. So because it never loads I don't get any kind of logs to post here.

**Comment by tashcan** [comment]
Did you update using the latest release (0.5.4)? https://github.com/tashcan/bob/releases/tag/v0.5.4

**Comment by michaelcrossland1979** [comment]
Thanks did not see that there was an update yet.
It works.
