### ISSUE TITLE
Building the Code

### ISSUE THREAD

**Issue by MDasky1** [tashcan/bob#18]
I installed the Community Edition of Visual Studio and was able to complete the build, however I usually use the JetBrains IDE, C Lion. It will not build there. Just wondering if anyone else uses C Lion and what I need to do to make it work. I have the professional versions of all the JetBrains IDEs and am more comfortable working with them.

**Comment by tashcan** [comment]
I personally don't have CLion installed or used it ever really.
Any more context, do you get a specific error or something? 

It's a little surprising since CLion is supposed to be like CMake first, or am I wrong?

**Comment by MDasky1** [comment]
====================[ Build | all | Debug ]=====================================
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\cmake\win\x64\bin\cmake.exe" --build C:\Users\mdask\CLionProjects\bob\cmake-build-debug --target all -j 14
[1/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/main.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/main.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/main.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\main.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/main.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/main.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[2/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/utils.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/utils.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/utils.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\utils.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/utils.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/utils.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[3/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/version.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/version.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/version.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\version.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/version.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/version.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[4/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/mapkey.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/mapkey.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/mapkey.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\mapkey.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/mapkey.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/mapkey.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[5/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/key.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/key.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/key.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\key.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/key.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/key.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[6/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/parts/disable_banners.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/parts/disable_banners.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/parts/disable_banners.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\parts\disable_banners.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/parts/disable_banners.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/parts/disable_banners.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[7/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/parts/buff_fixes.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/parts/buff_fixes.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/parts/buff_fixes.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\parts\buff_fixes.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/parts/buff_fixes.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/parts/buff_fixes.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[8/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/modifierkey.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/modifierkey.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/modifierkey.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\modifierkey.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/modifierkey.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/modifierkey.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[9/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/il2cpp/il2cpp_helper.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/il2cpp/il2cpp_helper.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/il2cpp/il2cpp_helper.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\il2cpp\il2cpp_helper.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/il2cpp/il2cpp_helper.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/il2cpp/il2cpp_helper.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[10/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/config.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/config.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/config.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\config.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/config.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/config.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[11/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/parts/chat.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/parts/chat.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/parts/chat.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\parts\chat.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/parts/chat.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/parts/chat.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[12/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/patches.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/patches.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/patches.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\patches.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/patches.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/patches.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[13/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_unity_web_request.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_unity_web_request.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_unity_web_request.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\parts\fix_unity_web_request.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_unity_web_request.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/parts/fix_unity_web_request.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
[14/843] Building CXX object CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_pan.cc.obj
FAILED: CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_pan.cc.obj 
"C:\Users\mdask\AppData\Local\Programs\CLion Nova\bin\mingw\bin\g++.exe" -DJM_XORSTR_DISABLE_AVX_INTRINSICS -DSPDLOG_COMPILED_LIB -Dstfc_community_patch_EXPORTS -IC:/Users/mdask/CLionProjects/bob/stfc-community-patch -IC:/Users/mdask/CLionProjects/bob/third_party -IC:/Users/mdask/CLionProjects/bob/src -IC:/Users/mdask/CLionProjects/bob/src/patches -IC:/Users/mdask/CLionProjects/bob/third_party/xorstr/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/spud-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/json-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/src -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/protobuf-src/third_party/abseil-cpp -IC:/Users/mdask/CLionProjects/bob/third_party/spdlog/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eastl-src/include -IC:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/eabase-src/include/Common -isystem C:/Users/mdask/CLionProjects/bob/cmake-build-debug/_deps/tomlplusplus-src/include /std:c++latest /W4 /permissive- /bigobj /await -g -std=gnu++20 -fdiagnostics-color=always -MD -MT CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_pan.cc.obj -MF CMakeFiles\stfc-community-patch.dir\src\patches\parts\fix_pan.cc.obj.d -o CMakeFiles/stfc-community-patch.dir/src/patches/parts/fix_pan.cc.obj -c C:/Users/mdask/CLionProjects/bob/src/patches/parts/fix_pan.cc
g++.exe: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by MDasky1** [comment]
LOL, we were thinking the same thing. I set up an alternate toolchain for MSVC. Oddly, it builds just fine and I just tested it. The DLL file is a bit smaller then the one posted here
<img width="917" alt="toolchain" src="https://github.com/tashcan/bob/assets/36117316/393c6ed5-4780-46ba-b714-ba4d6e65b6ba">
